apiVersion: skaffold/v2beta9
kind: Config
metadata:
  name: appointment-bot
build:
  artifacts:
    - image: registry.webzyno.com/appointment-bot/app
      context: .

profiles:
  - name: ci
    patches:
      - op: add
        path: /build/local
        value:
          push:
            true
      - op: add
        path: /build/tagPolicy
        value:
          envTemplate:
            template: "{{.IMAGE_NAME}}:dirty-{{.GIT_COMMIT}}"
  - name: ci:release
    patches:
      - op: add
        path: /build/local
        value:
          push:
            false
      - op: add
        path: /build/tagPolicy
        value:
          envTemplate:
            template: "{{.IMAGE_NAME}}:{{.TAG_NAME}}"